### ISSUE TITLE
出现错误时前端应展示后端发来的message

### ISSUE THREAD

**Issue by KYLN24** [OpenTreeHole/treehole_frontend#20]
出现错误时前端应展示后端发来的message，避免出现使用户疑惑的描述

如，用户修改密码时
![R2$)76O5R}}T} T9236XT@C](https://user-images.githubusercontent.com/54014142/156735437-1e782150-ee00-4624-a3f1-fa76c2c74246.jpg)

后端传来的描述为
![$ZE QXMU3@`0HMC H3VIJ~G](https://user-images.githubusercontent.com/54014142/156735394-a35e5475-77c5-4ec6-9303-e7ee28f1fbf8.png)

如果用户看到了这个message，就不会感到疑惑了

**Comment by KYLN24** [comment]
修正：这不是message，所以前端可以考虑留一个“详细信息”按钮以查看 response 中的部分重要信息

**Comment by dest1n1s** [comment]
已解决
